### ISSUE TITLE
Multiple flag conflicts with subcommands

### ISSUE THREAD

**Issue by strangedev** [thenativeweb/command-line-interface#245]
When using a command option with `multiple: 'on'` and also define subcommands, there is ambiguity.
Consider the following example, where we've got some tool which has some option `-e` that can be repeated and also a subcommand `sub`.

```shell
some-tool -e argsAreFun suchANiceArg sub
```

In this example, `sub` could either refer to a value for `-e`, or be the name of a subcommand.
The current behavior is to consume as many arguments as possible before the next flag is matched.

@dotKuro and I had a discussion about how this could be resolved and we currently see two options:

1. Do away with the current syntax and use the flag repeatedly

With this, the new syntax would be:

```shell
some-tool -e argsAreFun -e suchANiceArg sub
```

This way, each occurence of a flag only consumes exactly one argument. I believe this is also how many shell-based tools handle this.

2. Implement non-deterministic parsing

We could also, whenever there is ambiguity, try to construct a valid command from all possible interpretations and see if any one of those actually creates a valid command. This could also lead us to situations, where more than one interpretation is valid. In this case we'd have to pick one of them, hence this being the non-deterministic option.

Also, for commands without subcommands, we could keep the old syntax, as there is no ambiguity there.

**Comment by goloroden** [comment]
Thanks for bringing up this issue 😊 

From my POV I'd definitely favor option 1 (having to repeat the flag), since this

- solves the issue in any case
- and can be used in the same way, no matter whether there is a sub-command or not.

So, to me this seems to be the most straight-forward and "there is only one way to do it" option.

**Comment by yeldiRium** [comment]
I agree that 1. is the best solution. The problematic behavior is the default behavior for the "multiple options" in [`command-line-args`](https://github.com/75lb/command-line-args) (see the [documentation](https://github.com/75lb/command-line-args/wiki/Greedy-multiples)).

We currently support the greedy multiple style (by setting `multiple` to `on`) and lazy style (by setting `multiple` to `lazy`).

I propose we drop the greedy support altogether, since I don't think we can resolve its conflict with our sub-comand approach. Let's make the `multiple` option into a simple boolean and use lazy multiple by default. This would be a breaking change, but in my opinion a necessary one.

**Comment by yeldiRium** [comment]
Out of scope here, but worth mentioning: We have a similar ambiguity problem with `default: true` options on commands that have sub-commands. That is probably more difficult to resolve.

**Comment by goloroden** [comment]
I like the approach @yeldiRium suggested (introducing a boolean flag instead of `on` and `lazy`) to disable the greedy style here.

WRT the option without spaces, but using a separate delimiter, from my POV the effort is not worth the outcome.

**Comment by strangedev** [comment]
One potential problem I see with removing greedy matching altogether is that we couldn't use shell globs anymore.
Maybe we should allow greedy matching only for "leaf" commands, i.e. commands without subcommands?

**Comment by strangedev** [comment]
To clarify what I mean by my last comment, consider the following example:

Suppose I want to write a tool that operates on a bunch of files, maybe a formatting tool of some sort. Then I would want to write a CLI which looks like:

```shell
nifty-tool --some-flag --files *.md
```

This would not work with a repeated flag, since the glob is expanded to a space-separated list of file names like this:

```shell
nifty-tool --some-flag --files file_a.md file_b.md file_c.md
```

 I'd then have to somehow intersperse the results from the glob with the `--files` flag, which [is not straightforward in bash](https://stackoverflow.com/questions/1527049/how-can-i-join-elements-of-an-array-in-bash).
 
Removing the ability to pass globs would essentially mean having to add pattern matching code inside every tool that needs such functionality (which would likely be some incarnation of glob itself).

**Comment by yeldiRium** [comment]
That makes a lot of sense, thanks for the clarification.

However, I don't think this will be much of a problem, although it is good to keep in mind. When working with input files, most of the time the option that takes these files will be a `defaultOption` and can thus omit the `--files` part. If the option `files` has `defaultOption: true` set, the following commands are equivalent:

```shell
$ nifty-tool --files file_a.md --files file_b.md
$ nifty-tool file_a.md file_b.md
# and assuming only file_a.md and file_b.md exist, this is also equivalent:
$ nifty-tool *.md
```

This is of course still a problem if a command has multiple different options which are defined as `multiple: true` and which should all work with globs. E.g. if a command has an option `--input-files` and an option `--output-files` or something like that. Is that likely and something we want to consider?

**Comment by strangedev** [comment]
Thanks, I didn't know about `defaultOption`. I don't think globs are likely to occur twice in a single invocation. I don't think that is a case we should consider.

I don't know about the internals of `defaultOption`, but it'd be interesting to know if it uses greedy or lazy matching. If it is greedy, it is likely to cause problems in non-leaf commands as well, although it is not obvious to me why one would do such a thing. Default options in a non-leaf command are easily confused with subcommands and I don't think we should encourage this pattern.

So it seems to me that `multiple` should always be lazy, `defaultOptions` should always be greedy and only valid in a non-leaf command.

What are your thoughts on this?

**Comment by yeldiRium** [comment]
> If it is greedy, it is likely to cause problems in non-leaf commands as well

Yes, that is what I meant in my [comment further above](https://github.com/thenativeweb/command-line-interface/issues/245#issuecomment-756411987).

I think we should move this part of the discussion into a separate issue. I agree with your opinion that `defaultOption` should always be greedy (which it is) and only be valid in a leaf command. Since this is validation and not execution, I'd fix this separately. I'll open an issue for it.
